Store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.index, name='index'),
    path('products/', views.products, name='products'),
    path('products/<int:category_id>/', views.products, name='category'),
    path('page/<int:page>', views.products, name='page'),
    path('basket-add/<int:product_id>/', views.basket_add, name='basket_add'),
    path('basket-delete/<int:basket_id>/', views.basket_delete, name='basket_delete'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
]

products/models.py
from django.db import models
from users.models import User


class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True)
    description = models.TextField(blank=True)

    class Meta:
        verbose_name_plural = 'Products Categories'

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=256)
    image = models.ImageField(upload_to='products_images', blank=True)
    description = models.TextField(blank=True)
    short_description = models.CharField(max_length=64)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} | {self.category}"


class Basket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Корзина для {self.user.username} | Продукт {self.product.name}'

    def sum(self):
        return self.quantity * self.product.price

products/views.py
from django.shortcuts import render, HttpResponseRedirect
from .models import ProductCategory, Product, Basket
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator


def index(request):
    return render(request, 'products/index.html')


def products(request, category_id=None, page=1):
    context = {
        'categories': ProductCategory.objects.all(),
    }
    if category_id:
        products = Product.objects.filter(category_id=category_id)
    else:
        products = Product.objects.all()
    paginator = Paginator(products, 3)
    products_paginator = paginator.page(page)
    context.update({'products': products_paginator})
    return render(request, 'products/products.html', context)


@login_required
def basket_add(request, product_id):
    product = Product.objects.get(id=product_id)
    baskets = Basket.objects.filter(user=request.user, product=product)

    if not baskets.exists():
        Basket.objects.create(user=request.user, product=product, quantity=1)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        basket = baskets.first()
        basket.quantity += 1
        basket.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_delete(request, basket_id):
    if Basket.objects.get(id=basket_id).quantity == 1:
        basket = Basket.objects.get(id=basket_id)
        basket.delete()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        basket = Basket.objects.get(id=basket_id)
        basket.quantity -= 1
        basket.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


templates/products/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link type="text/css" rel="stylesheet" href="{% static 'products/css/base.css' %}" />
    {% block styles %}
    {% endblock %}
    <title>{% block title %}General Store{% endblock %}</title>
</head>
<body>
    <header>
        <div class="container">
            <div class="header-line">
                <div class="logo">
                    <a href="{% url 'products:index' %}">
                        GeneralStore
                    </a>
                </div>

                <div class="nav">
                    <a href="{% url 'products:products' %}">Каталог</a>
                    {% if user.is_authenticated %}
                        <a href="{% url 'users:profile' %}">{{ user.username  }}</a>
                        <a href="{% url 'users:logout' %}">Выйти</a>
                    {% else %}
                        <a href="{% url 'users:login' %}">Войти</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </header>
    {% block content %}
    {% endblock %}
</body>
</html>

templates/products/basket.html
{% if baskets %}
    <div class="basket">
    <div class="title-and-quantity-goods">
        <div class="title">Корзина</div>
        <div class="quantity-goods"> {{ total_quantity }}</div>
    </div>
    <div class="product">
        {% for basket in baskets %}
            <div class="product-name-description">
                <div class="product-name">{{ basket.product.name }}</div>
                <div class="product-description">{{ basket.product.short_description }}</div>
            </div>
            <div class="quantity-price-delete">
                <div class="quantity">{{ basket.quantity }} шт.</div>
                <div class="price">{{ basket.sum }} руб.</div>
                <div class="buttons-add-delete">
                    <a href="{% url 'products:basket_delete' basket.id %}">
                        <button class="btn btn-danger" type="submit"> - </button>
                    </a>
                    <a href="{% url 'products:basket_add' basket.product.id %}">
                        <button class="btn btn-success" type="submit"> + </button>
                    </a>
                </div>
            </div>
        {% endfor %}
        <div class="block-finally-price">
            <div class="itogo">Итого</div>
            <div class="finally-price">{{ total_sum }} руб.</div>
        </div>
       <button type="button" class="btn btn-success btn-formalize" type="submit">Оформить</button>
    </div>
</div>
{% else %}
    <div class="title">Корзина пуста</div>
{% endif %}


templates/products/index.html
{% extends 'products/base.html' %}
{% load static %}
{% block styles %}
    <link type="text/css" rel="stylesheet" href="{% static 'products/css/index.css' %}">
{% endblock %}

{% block content %}
    <div class="main_button">
        <a href="{% url 'products:products' %}"> К покупкам </a>
    </div>
{% endblock %}

templates/products/products.html
{% extends 'products/base.html' %}
{% load static %}
{% block styles %}
    <link rel="stylesheet" href="{% static 'products/css/products.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
{% endblock %}
{% block title %}
    Products
{% endblock %}

{% block content %}
    <div class="container">
        <div class="categories-and-goods">
            <div class="categories" style="border-top: 1px solid black; border-radius: 2px">
                <a href="{% url 'products:products' %}">Все товары</a>
                {% for category in categories %}
                    <a href="{% url 'products:category' category.id %}">{{ category.name }}</a>
                {% endfor %}
            </div>
            <div class="goods">
                {% for product in products %}
                    <div class="product">
                        <img src="/media/{{ product.image }}" alt="">
                        <div class="text-in-product">
                            <div class="name">{{ product.name }}</div>
                            <div class="price">{{ product.price }} руб</div>
                            <div class="short-description">{{ product.short_description }}</div>
                        </div>
                        <div class="block-button">
                            <a href="{% url 'products:basket_add' product.id %}">
                                <button class="button" type="button">Добавить в корзину</button>
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <li class="page-item {% if not products.has_previous %} disabled {% endif %}">
                        <a class="page-link"
                           href="{% if products.has_previous %} {% url 'products:page' products.previous_page_number %} {% else %} # {% endif %}"
                           tabindex="-1" aria-disabled="true">Предыдущая</a>
                    </li>
                    {% for page in products.paginator.page_range %}
                        <li class="page-item"><a class="page-link" href="{% url 'products:page' page %}">{{ page }}</a></li>
                    {% endfor %}
                    <li class="page-item {% if not products.has_next %} disabled {% endif %}">
                        <a class="page-link"
                           href="{% if products.has_next %} {% url 'products:page' products.next_page_number %} {% else %} # {% endif %}">
                            Следующая
                        </a>
                    </li>
                </ul>
            </nav>
    </div>
{% endblock %}

templates/products/profile.html
{% extends 'products/base.html' %}
{% load static %}
{% block styles %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'products/css/profile.css' %}">
    <link rel="stylesheet" href="{% static 'products/css/base.css' %}">
{% endblock %}
{% block content %}
    <div class="container">
        <div class="profile-and-basket">
            <div class="profile">
                <form action="{% url 'users:profile' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="title">Профиль</div>
                    <img src="{% if user.image %} {{ user.image.url }} {% else %}
                    {% static 'products/images/default-avatar.jpg' %} {% endif %}" alt="#">
                    <div class="first-and-last-name">
                        <div class="first-name">
                            <div class="label">Имя</div>
                            {{ form.first_name }}
                        </div>
                        <div class="last-name">
                            <div class="label">Фамилия</div>
                            {{ form.last_name }}
                        </div>
                    </div>
                    <div class="form-row md-2">
                        <div class="col-lg-12">
                            <div class="custom-file">
                                {{ form.image }}
                                <label class="custom-file-label" for="userAvatar">Выберите изображение</label>
                            </div>
                        </div>
                    </div>
                    <div class="username-and-email">
                        <div class="username-block">
                            <div class="label">Имя пользователя</div>
                            {{ form.username }}
                        </div>
                        <div class="email-block">
                            <div class="label">Адрес электронной почты</div>
                            {{ form.email }}
                        </div>
                    </div>
                    <button type="submit" class="button-save">Сохранить</button>
                </form>
            </div>
            {% include 'products/basket.html' %}
        </div>
    </div>
{% endblock %}